Provide messageArguments for exceptions
kbss-cvut/fta-fmea pull request #158
Opened 2024-09-16 13:15 UTC by palagdan

Resolves partially #kbss-cvut/fta-fmea-ui#550

2024-09-18 09:21 UTC, blcham requested changes
LGTM, just see my comments

2024-09-18 09:34 UTC, palagdan commented on src/main/java/cz/cvut/kbss/analysis/model/fta/FTAMinimalCutSetEvaluation.java
> +                            .collect(Collectors.joining("\n"));
No, it wasn't just for the default message. It looked correct on the frontend. I've fixed it.

![Screenshot from 2024-09-18 11-31-44](https://github.com/user-attachments/assets/3e7dd8f9-3b23-429c-a9cd-7a85707ddcb8)

2024-09-18 09:34 UTC, palagdan commented on src/main/java/cz/cvut/kbss/analysis/service/SystemRepositoryService.java
> +                    ("System with name\"%s\" already exists")
done

2024-09-23 16:21 UTC, blcham approved these changes

2024-09-23 16:21 UTC, blcham commented on src/main/java/cz/cvut/kbss/analysis/model/fta/FTAMinimalCutSetEvaluation.java
> +                            .collect(Collectors.joining("\n"));
ok

2024-09-23 16:21 UTC, merged